import test from 'node:test';
import assert from 'node:assert/strict';
import { initialState, transition, digest, minor, apply } from '../skills/woia-payments/scripts/payments.mjs';
const scope={currency:'XTS',scale:2,account:'synthetic-account',beneficiary:'synthetic-beneficiary',custody:'synthetic-custody',purpose:'synthetic-purpose'};
const now='2026-10-07T12:00:00Z',from='2026-10-01T00:00:00Z',until='2026-11-01T00:00:00Z';
function command(state,action,target,payload,operation_key=`op-${state.revision}`){return {org:state.org,action,target,payload,operation_key,expected_revision:state.revision};}
function context(c,extra={}){return {org:c.org,actor:'synthetic-finance',task:'synthetic-task',authenticated:true,department:'Finance',capability:'woia-payments',admitted:true,emergency_stop:false,now,policy:{id:'policy',version:'1',digest:'policy-digest',revoked:false,from,until},grant:{id:'grant',revision:'1',issuer:'synthetic-policy-owner',actor:'synthetic-finance',task:'synthetic-task',org:c.org,operation:c.action,target:c.target,policy_digest:'policy-digest',revoked:false,from,until},source_verification:{payload_digest:digest(c.payload),verified:true,fresh:true,conflict:false},source_rule:{org:c.org,account:scope.account,namespace:'synthetic-bank',version:'source-v1',conflict:false,writer:'woia-payments',revoked:false,fresh:true,from,until,modes:['PROVIDER_CONFIRMED','COMPETENT_HUMAN_CONFIRMED','DIRECT_TO_BENEFICIARY_CONFIRMED'],human_confirmers:['synthetic-human']},...extra};}
function step(state,action,target,payload,extra={}){const c=command(state,action,target,payload);return transition(state,c,context(c,extra));}
function observed(){return step(initialState('org-a'),'payment.observe','obs-1',{...scope,id:'obs-1',namespace:'synthetic-bank',source_id:'tx-1',source_version:'v1',evidence:'synthetic-evidence',occurred_at:now,minor:'1000',status:'CONFIRMED'}).state;}
function accepted(mode='PROVIDER_CONFIRMED',extra={}){const payload={...scope,minor:'1000',observation_id:'obs-1',source_map_version:'source-v1',payer:'synthetic-payer',direction:'INBOUND',confirmation_mode:mode};return step(observed(),'payment.accept','pay-1',payload,{acceptance_confirmation:{payload_digest:digest(payload),observation_id:'obs-1',mode},...extra}).state;}
const funds={payment_id:'pay-1',revision:'funds-1',hold:false,purpose_allowed:true,fresh:true};
function reserved(){return step(accepted(),'payment.reserve','res-1',{...scope,minor:'600',payment_id:'pay-1',hold:false,funds_revision:'funds-1'},{funds}).state;}
function execution(state=reserved()){const c=command(state,'payment.execute','effect-1',{...scope,minor:'600',fee_minor:'0',reservation_id:'res-1',provider_operation:'synthetic-provider-op',funds_revision:'funds-1'});const ctx=context(c,{funds,aggregate:{current:true,account:scope.account,currency:scope.currency,scale:scope.scale,remaining_minor:'600'},adapter:{configured:true,qualified:true,account:scope.account,notifications_suppressed:true},approval:{id:'approval',revision:'1',org:c.org,operation:c.action,target:c.target,actor:'synthetic-finance',task:'synthetic-task',approver:'synthetic-human',competent:true,revoked:false,policy_digest:'policy-digest',payload_digest:digest(c.payload),from,until}});return {c,ctx,out:transition(state,c,ctx)};}
function receipt(state,status,amount){return step(state,'payment.effect.reconcile','effect-1',{}, {receipt:{verified:true,org:state.org,effect_id:'effect-1',provider_operation:'synthetic-provider-op',evidence:'synthetic-receipt',status,confirmed_minor:amount,currency:'XTS',scale:2}}).state;}
test('exact minor units reject floats, negatives and non-canonical strings',()=>{assert.equal(minor('9007199254740993'),9007199254740993n);for(const x of [1.1,'1.1','-1','01'])assert.throws(()=>minor(x));});
test('observation is evidence and leaves accepted funds empty',()=>{const s=observed();assert.equal(s.observations['obs-1'].kind,'PaymentObservation');assert.deepEqual(s.payments,{});});
test('trustworthy source verification is payload bound',()=>{const c=command(initialState('org-a'),'payment.observe','o',{...scope,id:'o',namespace:'x',source_id:'t',source_version:'1',evidence:'e',occurred_at:now,minor:'1'});assert.throws(()=>transition(initialState('org-a'),c,context(c,{source_verification:{payload_digest:'wrong'}})),/SOURCE_VERIFICATION/);});
test('provider-confirmed acceptance creates one immutable Payment',()=>{const s=accepted();assert.equal(s.payments['pay-1'].kind,'Payment');assert.equal(s.observations['obs-1'].kind,'PaymentObservation');});
test('source authority, freshness and confirmation modes fail closed',()=>{for(const changes of [{source_rule:null},{source_rule:{...context({payload:{},org:'org-a'}).source_rule,fresh:false}},{source_rule:{...context({payload:{},org:'org-a'}).source_rule,modes:[]}}])assert.throws(()=>accepted('PROVIDER_CONFIRMED',changes));});
test('competent human requires exact configured confirmer and evidence',()=>{assert.throws(()=>accepted('COMPETENT_HUMAN_CONFIRMED'));assert.equal(accepted('COMPETENT_HUMAN_CONFIRMED',{confirmation:{competent:true,actor:'synthetic-human',evidence:'synthetic-evidence'}}).payments['pay-1'].confirmation_mode,'COMPETENT_HUMAN_CONFIRMED');});
test('duplicate source fact cannot mint another accepted Payment',()=>{const s=accepted(),payload={...s.payments['pay-1']};assert.throws(()=>step(s,'payment.accept','pay-2',payload,{acceptance_confirmation:{payload_digest:digest(payload),observation_id:'obs-1',mode:'PROVIDER_CONFIRMED'}}),/DUPLICATE_SOURCE_FACT/);});
test('org, department, grant issuer and stale revisions deny mutation',()=>{const s=observed(),c=command(s,'payment.reserve','r',{});for(const x of [{org:'other'},{department:'Sales'},{grant:null}])assert.throws(()=>transition(s,c,context(c,x)));assert.throws(()=>transition(s,{...c,expected_revision:0},context(c)),/STALE_REVISION/);});
test('reservation locks exact eligible funds and prevents aggregate competing consumption',()=>{const s=reserved();assert.equal(s.reservations['res-1'].remaining,'600');assert.throws(()=>step(s,'payment.reserve','res-2',{...scope,minor:'500',payment_id:'pay-1',hold:false,funds_revision:'funds-1'},{funds}),/INSUFFICIENT/);});
test('held, wrong beneficiary and cross-currency funds cannot reserve',()=>{for(const p of [{...scope,beneficiary:'other'},{...scope,currency:'OTHER'}])assert.throws(()=>step(accepted(),'payment.reserve','r',{...p,minor:'100',payment_id:'pay-1',hold:false,funds_revision:'funds-1'},{funds}),/SCOPE_MISMATCH/);assert.throws(()=>step(accepted(),'payment.reserve','r',{...scope,minor:'100',payment_id:'pay-1',hold:false,funds_revision:'funds-1'},{funds:{...funds,hold:true}}),/FUNDS_ELIGIBILITY/);});
test('execute persists UNKNOWN before dispatch and retains reservation',()=>{const {out}=execution();assert.equal(out.dispatch.persist_before_dispatch,true);assert.equal(out.state.effects['effect-1'].status,'UNKNOWN');assert.equal(out.state.reservations['res-1'].remaining,'600');});
test('changed approval payload, revoked approval and aggregate limit deny execution',()=>{const {c,ctx}=execution();for(const x of [{...ctx,approval:{...ctx.approval,payload_digest:'wrong'}},{...ctx,approval:{...ctx.approval,revoked:true}},{...ctx,aggregate:{...ctx.aggregate,remaining_minor:'599'}}])assert.throws(()=>transition(reserved(),c,x));});
test('unknown or partial effects block retries and reservation release',()=>{const s=execution().out.state;assert.throws(()=>execution(s),/RECONCILE_BEFORE_RETRY/);assert.throws(()=>step(s,'payment.release-reservation','res-1',{}),/RECONCILE_BEFORE_RELEASE/);});
test('same operation replay never emits a second dispatch',()=>{const {c,ctx,out}=execution();const replay={...c,expected_revision:out.state.revision};const retried=transition(out.state,replay,ctx);assert.equal(retried.dispatch,null);assert.deepEqual(retried.state,out.state);});
test('partial confirmation consumes only confirmed amount and retains remainder',()=>{const s=receipt(execution().out.state,'PARTIAL','200');assert.equal(s.reservations['res-1'].consumed,'200');assert.equal(s.reservations['res-1'].remaining,'400');const done=receipt(s,'SUCCEEDED','600');assert.equal(done.reservations['res-1'].remaining,'0');});
test('wrong effect receipt, currency and terminal overwrite fail closed',()=>{const s=execution().out.state;assert.throws(()=>step(s,'payment.effect.reconcile','effect-1',{}, {receipt:{verified:true,org:'other'}}),/VERIFIED_SAME_EFFECT/);assert.throws(()=>receipt(s,'SUCCEEDED','200'),/STATUS_AMOUNT/);assert.throws(()=>receipt(receipt(s,'SUCCEEDED','600'),'FAILED','0'));});
test('status reads retain exact effect identity without changing revision',()=>{const s=execution().out.state;const c=command(s,'payment.status.observe','effect-1',{});assert.equal(transition(s,c,context(c)).state.revision,s.revision);});
test('atomic store must commit before an outbox dispatcher can act',async()=>{const {c,ctx}=execution();let committed;const store={async transaction(org,fn){assert.equal(org,'org-a');const result=await fn(reserved());committed=result.state;return result;}};const out=await apply(store,c,async()=>ctx);assert.equal(committed.effects['effect-1'].status,'UNKNOWN');assert.ok(out.dispatch);await assert.rejects(()=>apply({},c,async()=>ctx),/ATOMIC_STORE/);});
test('accepted scope and confirmation cannot be altered from observed facts',()=>{assert.throws(()=>accepted('PROVIDER_CONFIRMED',{acceptance_confirmation:null}),/ACCEPTANCE_CONFIRMATION/);const payload={...scope,beneficiary:'different-beneficiary',minor:'1000',observation_id:'obs-1',source_map_version:'source-v1',payer:'p',direction:'INBOUND',confirmation_mode:'PROVIDER_CONFIRMED'};assert.throws(()=>step(observed(),'payment.accept','p',payload,{acceptance_confirmation:{payload_digest:digest(payload),observation_id:'obs-1',mode:'PROVIDER_CONFIRMED'}}),/OBSERVED_SCOPE/);});
test('direct beneficiary acceptance never fabricates agency custody or payout eligibility',()=>{const obs={...scope,custody:'DIRECT_TO_BENEFICIARY',id:'obs-1',namespace:'synthetic-bank',source_id:'tx-1',source_version:'v1',evidence:'synthetic-evidence',occurred_at:now,minor:'1000',status:'CONFIRMED'};const s=step(initialState('org-a'),'payment.observe','obs-1',obs).state;const payload={...scope,custody:'DIRECT_TO_BENEFICIARY',minor:'1000',observation_id:'obs-1',source_map_version:'source-v1',payer:'p',direction:'INBOUND',confirmation_mode:'DIRECT_TO_BENEFICIARY_CONFIRMED'};const accepted=step(s,'payment.accept','pay-1',payload,{acceptance_confirmation:{payload_digest:digest(payload),observation_id:'obs-1',mode:payload.confirmation_mode}}).state;assert.throws(()=>step(accepted,'payment.reserve','r',{...payload,payment_id:'pay-1',hold:false,funds_revision:'funds-1'},{funds}),/NO_ELIGIBLE_CUSTODIED_FUNDS/);});
test('payment reconciliation appends evidence without rewriting accepted money',()=>{const s=accepted(),before=structuredClone(s.payments['pay-1']);const next=step(s,'payment.reconcile','pay-1',{observation_id:'obs-1',evidence:'synthetic-reconciliation',source_version:'v1',source_map_version:'source-v1',status:'DISPUTED'}).state;assert.deepEqual(next.payments['pay-1'],before);assert.equal(next.reconciliation[0].status,'DISPUTED');});
test('disputed/reversed payment reconciliation blocks even apparently eligible funds',()=>{for(const status of ['DISPUTED','REVERSED','UNKNOWN']){const s=step(accepted(),'payment.reconcile','pay-1',{observation_id:'obs-1',evidence:'synthetic-reconciliation',source_version:'v1',source_map_version:'source-v1',status}).state;assert.throws(()=>step(s,'payment.reserve','r',{...scope,minor:'100',payment_id:'pay-1',hold:false,funds_revision:'funds-1'},{funds}),/RECONCILIATION_BLOCKS/);const r=step(reserved(),'payment.reconcile','pay-1',{observation_id:'obs-1',evidence:'synthetic-reconciliation',source_version:'v1',source_map_version:'source-v1',status}).state;assert.throws(()=>execution(r),/RECONCILIATION_BLOCKS/);}});
test('confirmed failed effect can release unconsumed reservation only with exact approval',()=>{const s=receipt(execution().out.state,'FAILED','0');const c=command(s,'payment.release-reservation','res-1',{reason:'synthetic-failure'});const ctx=context(c,{approval:{id:'release-approval',revision:'1',org:c.org,operation:c.action,target:c.target,actor:'synthetic-finance',task:'synthetic-task',approver:'synthetic-human',competent:true,revoked:false,policy_digest:'policy-digest',payload_digest:digest(c.payload),from,until}});assert.throws(()=>transition(s,c,context(c)),/EXACT_APPROVAL/);const next=transition(s,c,ctx).state;assert.equal(next.reservations['res-1'].remaining,'0');assert.equal(next.reservations['res-1'].consumed,'0');assert.equal(next.effects['effect-1'].status,'FAILED');});
